apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    name:  my-name
spec:
  replicas: 5
  selector:
    matchLables:
      server: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        server: nginx
    spec:
      containers:
      - image:  nginx:latest
        name:  my-name
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
          limits:
            cpu: "128m"
            memory: "500Mi"
        ports:
        - containerPort:  5000
          name:  my-name
